### ISSUE TITLE
Trailing comma in Table of Authorities

### ISSUE THREAD

**Issue by frabyn** [frabyn/simon-brief#12]
There is a trailing comma in the Table of Authorities entry for the example case Wilson v. State. This may be a product of how Lawtex parses the citations.

It may be helpful to refer back to the original project https://sourceforge.net/projects/lawtex/

Adapt the citation parsing to process this format, of a Texas state case, and prevent the trailing comma.

**Comment by AndreyBPopov** [comment]
Please write more details on this issue. I can't find mentioned trailing comma in PDF.

**Comment by frabyn** [comment]
I updated the PDF in the repository to reflect the issue. Also I'm noticing the spacing between characters in the table of authorities is uneven. Is there some kind of justification going on that we can eliminate?

**Comment by AndreyBPopov** [comment]
I have empty table of authority after processing .tex on my PC, how you process the file? On my PC I just run pdflatex simon-brief.tex...

**Comment by frabyn** [comment]
Oh gosh, the standard github gitignore excluded some critical build files. Sorry! Just fixed it.

**Comment by AndreyBPopov** [comment]
The important file lawcitations.ist was absent too. I put it to github. Please take a look now.

**Comment by AndreyBPopov** [comment]
Also please look here
http://tug.ctan.org/macros/latex/exptl/biblatex-contrib/oscola/oscola.pdf
May be that package will be useful for you too.

**Comment by frabyn** [comment]
I will take a look! Thank you so much. Works now, closing.
