### ISSUE TITLE
Implement proper curly quotes

### ISSUE THREAD

**Issue by frabyn** [frabyn/simon-brief#13]
Quotes currently are straight, and need to be processed to be curly

**Comment by AndreyBPopov** [comment]
In fact, this not a bug. It is because you use utf8 encoding. I have added \usepackage[utf8]{inputenc} to preamble to fix that. Also you may use `` --- for the opening quote and '' --- for the closing quote.

**Comment by frabyn** [comment]
Ah! Ok!
