### ISSUE TITLE
New line of text on cover page

### ISSUE THREAD

**Issue by frabyn** [frabyn/simon-brief#15]
The cover page needs to say "Oral Argument Requested"

Please put this centered, above the bottom horizontal line.

**Comment by AndreyBPopov** [comment]
I see three short horizontal lines at cover page. Should I add "Oral Argument Requested" below line below "B RIEF FOR A PPELLANT", i.e.
----------------------
BRIEF FOR APPELLANT
-----------------------
Oral Argument Requested

or in another place?

**Comment by AndreyBPopov** [comment]
Also since the title page is generated automatically, are there another variations of the text "Oral Argument Requested"? May be a special command for such text is needed here?

**Comment by frabyn** [comment]
There is only one other variation: "oral argument not requested" and also an option for no text. 

Please place it at the bottom of the page below the Appellant's lawyer information and above the bottom line

**Comment by AndreyBPopov** [comment]
Completed.
