### ISSUE TITLE
/s/ needs to be followed by the name of the signer

### ISSUE THREAD

**Issue by frabyn** [frabyn/simon-brief#16]
Currently the document leaves /s/ for signature lines. The /s/ needs to be followed by the name of the signer that is produced below the signature line.

Currently:
/s/
Franklin Bynum

New:
/s/ Franklin Bynum
Franklin Bynum

**Comment by AndreyBPopov** [comment]
The "Franklin Bynum" below horizontal line is typed by Small Caps font, what font I should use above the line: Small Caps or Normal?

**Comment by frabyn** [comment]
Small caps

**Comment by frabyn** [comment]
Wait, no make it regular caps

**Comment by AndreyBPopov** [comment]
Completed. Please check, I'm not sure about the result.

**Comment by frabyn** [comment]
Ok, I took a look. Sorry to be unclear before. The name should be in title case: 

/s/ Franklin Bynum

Also, the line should continue underneath the signature. Currently the signature line does not appear until after name.

**Comment by AndreyBPopov** [comment]
Completed.
