### ISSUE TITLE
Add ability to add second lawyer

### ISSUE THREAD

**Issue by frabyn** [frabyn/simon-brief#18]
In some cases, two lawyers will handle an appeal. In those cases, the lead lawyer should appear in the same place in the cover page. 

The second lawyer should appear to the left of the lead lawyer, flush with the left margin.

Perhaps call the field lawyer2?

\lawyer2{Joe Johnson}
\lawyer2position{Counsel for Appellant}
\lawyer2bar{Texas Bar \# 123456}
\lawyer2address{123 Main Street\\Houston, Texas 77004\\+1 713 343 8844\\joe@johnson.com}

If there is no lawyer2 information, the space to the left of the lead counsel should be blank as it is now.

**Comment by AndreyBPopov** [comment]
Completed.

**Comment by AndreyBPopov** [comment]
It is not possible to use number in LaTeX commands, so I used \SecondaryLawyer instead of \lawyer2 and also \LeadLawyer instead of \author.
