### ISSUE TITLE
Add bar number field

### ISSUE THREAD

**Issue by frabyn** [frabyn/simon-brief#19]
For author (and for lawyer2, see Issue 18) there should be a text field that appears under the "position" field. This is for the "bar number" of the lawyer.

So

\author{Franklin Bynum}
\authorposition{Lead Counsel for Appellant}
\authorbar{Texas Bar \#24069451}
\address{2814 Hamilton Street\\Houston, Texas 77004\\+1 713 343 8844\\franklin@bynumlaw.net}

This will throw off spacing on the cover page, please adjust so it still all fits on one page

**Comment by AndreyBPopov** [comment]
Completed.
