### ISSUE TITLE
Allow options to disable parts of document

### ISSUE THREAD

**Issue by frabyn** [frabyn/simon-brief#20]
Please add the option to disable the table of contents, table of authorities, and identification of parties. Some documents do not need those items.

**Comment by frabyn** [comment]
(If this isn't possible, then please create a new document class that removes those items.)

**Comment by AndreyBPopov** [comment]
Completed.

**Comment by AndreyBPopov** [comment]
Do we need print the secondary lawyer (if exists) in Identity of Parties and Counsel table?

**Comment by frabyn** [comment]
Not right now, no.
