### ISSUE TITLE
Expand court name options

### ISSUE THREAD

**Issue by frabyn** [frabyn/simon-brief#21]
Currently, the \coa function indicates which Texas Court of Appeals should be on the cover page.

(There are 14 courts of appeals in Texas, the First Court of Appeals, the Second Court of Appeals, and so on)

Since this document will also be used in courts other than, expand and rename the coa function to name different courts.

- rename function from coa to court
- the court function takes an argument for which court to fill in

Courts to add:
__All 14 Texas courts of appeals in this format:__
TXcoa1 == First Court of Appeals of Texas \\ at Houston 
TXcoa2 == Second Court of Appeals of Texas \\ at Fort Worth
TXcoa3 == Third Court of Appeals of Texas \\ at Austin
TXcoa4 == Fourth Court of Appeals of Texas \\ at San Antonio
TXcoa5 == Fifth Court of Appeals of Texas \\ at Dallas
TXcoa6 == Sixth Court of Appeals of Texas \\ at Texarkana
TXcoa7 == Seventh Court of Appeals of Texas \\ at Amarillo
TXcoa8 == Eighth Court of Appeals of Texas \\ at El Paso
TXcoa9 == Ninth Court of Appeals of Texas \\ at Beaumont
TXcoa10 == Tenth Court of Appeals of Texas \\ at Waco
TXcoa11 == Eleventh Court of Appeals of Texas \\ at Eastland
TXcoa12 == Twelfth Court of Appeals of Texas \\ at Tyler
TXcoa13 == Thirteenth Court of Appeals of Texas \\ at Corpus Christi
TXcoa14 == Fourteenth Court of Appeals of Texas \\ at Houston

__Higher Texas courts__
TXsc == Supreme Court of Texas
TXcca == Court of Criminal Appeals of Texas

__Federal courts of appeals__
USCA1 == United States Court of Appeals // for the First Circuit
USCA2 == United States Court of Appeals // for the Second Circuit
and so on through
USCA11

We will add trial courts later.

**Comment by AndreyBPopov** [comment]
Completed.
