### ISSUE TITLE
Add options for makefrontmatter

### ISSUE THREAD

**Issue by frabyn** [frabyn/simon-brief#22]
Right now, \makefrontmatter generates a cover page on the first page and then follows it with a page break.

To make the document more flexible for different styles, including styles that do not require a cover page, add options. 

__Current options__ 
\OralArgumentRequested

__New options__

- Make the following text optional, calling it "\appealfrom"
```
\smallrule

On Appeal from the District Court\\
\@trialcourt{} Judicial District \\
Case Number \@trialcase{}
```

- Make attorney information block optional
- Make page break optional. For some documents, we will simply want the cause number, the caption, the title, and then to begin with the document.

**Comment by AndreyBPopov** [comment]
Completed.
