### ISSUE TITLE
Add options for different type of appeal caption

### ISSUE THREAD

**Issue by frabyn** [frabyn/simon-brief#25]
Right now, as part of makefrontmatter, a "caption" is generated like this:

```
\@firstparty \\
\hfill \textit{\@firstpartytitle} \\
\textit{v.} \\
~\\
\@secondparty \\
\hfill \emph{\@secondpartytitle} \\
```

This is the caption for a kind of appeal that we will call informally a "v appeal". This is an appeal with an Appellant and an Appellee who are identified on either side of a v.

There is another kind of appeal caption, that we will call an "e appeal". This is an appeal with only one party. and no v. The party's name is preceded by language identifying the kind of action. Most commonly this will be "Ex parte". So, it would look like this:

```
\emph{Ex parte} \@firstparty
```

Add white space above and below the "v appeal" to make it take up comparable space to the "v appeal" caption, so that the cover page looks consistent between the two.

**Comment by AndreyBPopov** [comment]
Completed.
