### ISSUE TITLE
Adjust spacing of Identity of Parties and Counsel

### ISSUE THREAD

**Issue by frabyn** [frabyn/simon-brief#5]
Move right to the left by .3 inches

**Comment by AndreyBPopov** [comment]
What text must be moved by 0.3in?
(a) Left column, e.g. Defense Counsel at Trial, Prosecutors at Trial;
(b) Right column, e.g. Ryan Jusup Simon;
(c) Both columns;

**Comment by frabyn** [comment]
Sorry it was not clear! I meant for it to be (b). I intend for each line to fit without breaking automatically

**Comment by AndreyBPopov** [comment]
No problem. I will fix now.
