### ISSUE TITLE
Reduce indents in Table of Contents

### ISSUE THREAD

**Issue by frabyn** [frabyn/simon-brief#6]
Reduce all indents to .25 inches

**Comment by AndreyBPopov** [comment]
I'm not sure about indents. 
Now have changed the style to the following behaviour in TOC:
\section with no indent
\subsection indent 0.25in
\subsubsection indent is 0.25in to \subsection. i.e. 0.5in
\paragraph indent is 0.25 to \subsubsection, i.e. 0.75in
and so on...
